### ISSUE TITLE
ValueError when plotting 

### ISSUE THREAD

**Issue by nimonian** [k-donn/format-pi#8]
I'm plotting some basic trig graphs and I am occasionally getting
```
ValueError: 10.996 is not multiple of 1.571. Did you not use the .locator method?
```
Well I most surely did use the `.locator` method - is there some rounding issue going on? I notice that `3.5*np.pi` is `10.9955742875643` which, to be fair, is not a multiple of 1.571, but is nonetheless of the form `n*pi/2`. Generally, n to 3sf may not be divisible by m to 3sf even when (n/m) to 3sf is an int.

Also, could this be shown as a warning rather than crashing the program? I can't seem to get around it with a `try` block.

**Comment by k-donn** [comment]
Just to be clear. What parameters are you instantiaing the `MultiplePi` object with?

**Comment by k-donn** [comment]
Ok. I have done some testing.

With `MultiplePi(2)` so `pi/2`, 12.56637061435917 or `4pi` raises an error.

I cannot replicate the error with `3.5pi`, but I can with `4pi`.

The calculation for [numer](https://github.com/k-donn/format-pi/blob/master/matplot_fmt_pi/multiple.py#L130) should be 8. Instead, it is 7.999999999999999. This is a rounding issue.

I will look into finding a way to warn a user about plugging in a wrong value while solving the rounding issue.
